{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.10.0/okio-multiplatform-2.10.0.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pcggdrbhgrhzdoicyzf4zswwn4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio.klib",
          "url": "okio-iosx64-2.10.0.klib",
          "size": 260223,
          "sha512": "173ecbf83d0d102ad47507d679511bd18fe497b38d9c60a31783143734e7a469792d914d7e48d9036285fe38adef82a8099729f713754572ba69ce01a97bb943",
          "sha256": "aeec86cdb6356714df490b10b5c1fabda6f7d8a1861580e7b202c7baf1f0096a",
          "sha1": "2bc11052bb465ea50471e328c159f92439acbb53",
          "md5": "a0b1c27a232e51cc4a4bcba96ac14657"
        }
      ]
    }
  ]
}
