{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.10.0-sphere-1/okio-multiplatform-2.10.0-sphere-1.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.10.0-sphere-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sly4mzsf3fdylc7dycxq52m7m4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.10.0-sphere-1.jar",
          "url": "okio-2.10.0-sphere-1.jar",
          "size": 255505,
          "sha512": "4c524e5db164e122d45b2fb35bd923ac880c16c39f4d5d03f65d013ad0c2d273cbf5ae5690e1ed9e0187db33430c1dc216828a2d98ea9809071ce09daded9f5c",
          "sha256": "79f0ee724c21a43ce37a60bff3b7e0d27b6951e4cc8004a30ac04be010fc4113",
          "sha1": "5028002b9b488bae158eb2d04d07314e333be8b6",
          "md5": "37b06486515c3f89fa065290884022de"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.10.0-sphere-1.jar",
          "url": "okio-2.10.0-sphere-1.jar",
          "size": 255505,
          "sha512": "4c524e5db164e122d45b2fb35bd923ac880c16c39f4d5d03f65d013ad0c2d273cbf5ae5690e1ed9e0187db33430c1dc216828a2d98ea9809071ce09daded9f5c",
          "sha256": "79f0ee724c21a43ce37a60bff3b7e0d27b6951e4cc8004a30ac04be010fc4113",
          "sha1": "5028002b9b488bae158eb2d04d07314e333be8b6",
          "md5": "37b06486515c3f89fa065290884022de"
        }
      ]
    }
  ]
}
