{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.10.0/okio-multiplatform-2.10.0.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "isbqvgkdibbhjjici5gdu4p53u"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "okio-js-2.10.0.klib",
          "url": "okio-js-2.10.0.klib",
          "size": 272105,
          "sha512": "2721163cc513d4efc06e19dc92c69119fc4039e54249e8bd7b145a5444acb614d59e8403c4c97923e9b9bbbec71ce8fd3f51f69caaf297f8fc1ae89fe26371dd",
          "sha256": "9d3d5ddc54e0031c5cccfc0aa48535b84a699fab76df31826f9d3c76e0a38038",
          "sha1": "93593dc373de908dc9c6f64886ecd8fc10c590a3",
          "md5": "188a4630d082c729c04a4f5ff31eb156"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "okio-js-2.10.0.klib",
          "url": "okio-js-2.10.0.klib",
          "size": 272105,
          "sha512": "2721163cc513d4efc06e19dc92c69119fc4039e54249e8bd7b145a5444acb614d59e8403c4c97923e9b9bbbec71ce8fd3f51f69caaf297f8fc1ae89fe26371dd",
          "sha256": "9d3d5ddc54e0031c5cccfc0aa48535b84a699fab76df31826f9d3c76e0a38038",
          "sha1": "93593dc373de908dc9c6f64886ecd8fc10c590a3",
          "md5": "188a4630d082c729c04a4f5ff31eb156"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.10.0/okio-metadata-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.10.0"
      }
    }
  ]
}
