{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.10.0/okio-multiplatform-2.10.0.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pcggdrbhgrhzdoicyzf4zswwn4"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio.klib",
          "url": "okio-macosx64-2.10.0.klib",
          "size": 260286,
          "sha512": "23497f67084171ada3d0c8838d9ee1539e899451ba865a66ef57b953acc838f639a5362abcfc0f324e311e386671d516771da5482119ce8da9b85f1b09400229",
          "sha256": "77dca590a7151402f15ab0a9bd2058b0854fb3738e7066b09d55f0461c285836",
          "sha1": "e5915dd92a3b1e8fe3e471d8582cfd4cbe5f21ea",
          "md5": "246ebfc0898534ce48e7b30942d8222f"
        }
      ]
    }
  ]
}
