{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio-multiplatform/2.10.0/okio-multiplatform-2.10.0.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "isbqvgkdibbhjjici5gdu4p53u"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.10.0.jar",
          "url": "okio-2.10.0.jar",
          "size": 257098,
          "sha512": "d98b53c1f666cb66d8d8a79f710595f8eb0af66c65802ad341a41114d3710d5b49221e8b1baecfc8a32760e80a083da23bd0b003e49de1c03b51908fe9ffe61f",
          "sha256": "f52559bd8b01baf8f8781bc08ec8c7d1e72252c674b60df060807657650bb226",
          "sha1": "25748d5e9f816b78b223f00ec5e810cf908b03ea",
          "md5": "f763800164fe3162e94ac29332f9c3d1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.10.0.jar",
          "url": "okio-2.10.0.jar",
          "size": 257098,
          "sha512": "d98b53c1f666cb66d8d8a79f710595f8eb0af66c65802ad341a41114d3710d5b49221e8b1baecfc8a32760e80a083da23bd0b003e49de1c03b51908fe9ffe61f",
          "sha256": "f52559bd8b01baf8f8781bc08ec8c7d1e72252c674b60df060807657650bb226",
          "sha1": "25748d5e9f816b78b223f00ec5e810cf908b03ea",
          "md5": "f763800164fe3162e94ac29332f9c3d1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.10.0/okio-metadata-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.10.0"
      }
    }
  ]
}
