{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pcggdrbhgrhzdoicyzf4zswwn4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "okio-metadata-2.10.0.jar",
          "url": "okio-multiplatform-2.10.0.jar",
          "size": 18763,
          "sha512": "96bb7de01bf55b7e8f9cb85a3b0d8c1ac898edf5e143225ce0ab859d95c4d9ebb104a292526fd2390dedf1de76b0d26dceab8adaceb154ee7dd77eef34b48148",
          "sha256": "7a6fb07329e90b2d4e46b4e0d725eb7e291e2408d65b136ef5c2937974036d97",
          "sha1": "1f583025a444bd6cca9dd6d6bbb04aa8cb8b3109",
          "md5": "a896038ca6c91bd161b83d0a15b332ed"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-iosarm64/2.10.0/okio-iosarm64-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-iosarm64",
        "version": "2.10.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-iosx64/2.10.0/okio-iosx64-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-iosx64",
        "version": "2.10.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-js/2.10.0/okio-js-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-js",
        "version": "2.10.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-js/2.10.0/okio-js-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-js",
        "version": "2.10.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio/2.10.0/okio-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio",
        "version": "2.10.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio/2.10.0/okio-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio",
        "version": "2.10.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-linuxx64/2.10.0/okio-linuxx64-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-linuxx64",
        "version": "2.10.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-macosx64/2.10.0/okio-macosx64-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-macosx64",
        "version": "2.10.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-mingwx64/2.10.0/okio-mingwx64-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-mingwx64",
        "version": "2.10.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-watchosarm32/2.10.0/okio-watchosarm32-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-watchosarm32",
        "version": "2.10.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-watchosarm64/2.10.0/okio-watchosarm64-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-watchosarm64",
        "version": "2.10.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-watchosx86/2.10.0/okio-watchosx86-2.10.0.module",
        "group": "com.squareup.okio",
        "module": "okio-watchosx86",
        "version": "2.10.0"
      }
    }
  ]
}
